### ISSUE TITLE
Build Error: Cannot find module './checksums.json' (v15.0.0-wvvmp-beta.7)

### ISSUE THREAD

**Issue by coredev-uk** [castlabs/electron-releases#106]
Error occurring when building electron when you run `npm i`. Occurs when using `15.0.0-wvvmp-beta.7`

```
error /Project/node_modules/electron: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: /Project/node_modules/electron
Output:
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module './checksums.json'
Require stack:
- /Project/node_modules/electron/install.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/Project/node_modules/electron/install.js:45:70)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
```

Seems to be occurring on macOS and Linux.

**Comment by coredev-uk** [comment]
Seems to be a side effect of having `https://github.com/castlabs/electron-releases.git` set as the devDependencies for electron.

**Comment by coredev-uk** [comment]
Ignore the last comment, seems to be a bug on electron 15 beta, works fine on v12.1.1-wvvmp.

**Comment by khwaaj** [comment]
Thanks for your report, it appears there was an addition to the installation script in `v15` that was not taken into consideration in ECS. I'll make sure it gets fixed for `v15.0.0-beta.7` and onwards.

In the mean time the behavior can be overridden by setting an environment variable when executing the package handler, e.g:

```
electron_use_remote_checksums=1 npm i
```

**Comment by khwaaj** [comment]
This should be fixed now, but you may need to make sure your `package-lock.json` does not refer to the old `v15.0.0-wvvmp-beta.7` tag (and maybe even clear the relevant package handler cache entries, e.g. using `nom cache`).

**Comment by coredev-uk** [comment]
This is great, thanks.
